### ISSUE TITLE
Null reference error after upgrading to REDCap 13

### ISSUE THREAD

**Issue by lexikin** [monash-redcap/auto_complete_form_status_on_required_fields#1]
Hi,

We just upgraded REDCap from version 10.6.19 to 13.1 LTS and PHP 7.2.24 to 8.1.2

We've been getting notified about errors from the reporting system.

```
[This message was automatically generated by REDCap]

The 'auto_complete_form_status_on_required_fields' module threw the following exception when calling the hook method 'redcap_save_record':

TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/html/redcap/modules/auto_complete_form_status_on_required_fields_v1.2/AutoCompleteStatusRequiredFieldsModule.php:98
Stack trace:
#0 /var/www/html/redcap/modules/auto_complete_form_status_on_required_fields_v1.2/AutoCompleteStatusRequiredFieldsModule.php(98): in_array()
#1 /var/www/html/redcap/modules/auto_complete_form_status_on_required_fields_v1.2/AutoCompleteStatusRequiredFieldsModule.php(24): Monash\Helix\AutoCompleteStatusRequiredFieldsModule\AutoCompleteStatusRequiredFieldsModule->checkRequiredFields()
#2 /var/www/html/redcap/redcap_v13.1.26/ExternalModules/classes/ExternalModules.php(3254): Monash\Helix\AutoCompleteStatusRequiredFieldsModule\AutoCompleteStatusRequiredFieldsModule->redcap_save_record()
#3 /var/www/html/redcap/redcap_v13.1.26/ExternalModules/classes/ExternalModules.php(3403): ExternalModules\ExternalModules::startHook()
#4 /var/www/html/redcap/redcap_v13.1.26/ExternalModules/classes/ExternalModules.php(3436): ExternalModules\ExternalModules::ExternalModules\{closure}()
#5 /var/www/html/redcap/redcap_v13.1.26/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook()
#6 /var/www/html/redcap/redcap_v13.1.26/Classes/DataEntry.php(5908): Hooks::call()
#7 /var/www/html/redcap/redcap_v13.1.26/DataEntry/index.php(321): DataEntry::saveRecord()
#8 {main}
```

I don't know PHP, but it looks like ```$settings['instruments_to_be_checked']['value'];``` is returning a null reference, which causes an exception when passed into ```in_array()```?

**Comment by monash-redcap** [comment]
This was fixed in version 1.3
